### ISSUE TITLE
Unable to start kafka-manager server 2.0.0.2

### ISSUE THREAD

**Issue by ssg1205** [yahoo/CMAK#670]
Hi,
   I am unable to start Kafka manager server 2.0.0.2. Here are the logs -

`# ./kafka-manager -Dconfig.file=conf/application.conf -Dhttp.port=8080 &`
`[1] 17377`
`[root@xyz bin]# Oops, cannot start the server.`
`java.lang.RuntimeException: No application loader is configured. Please configure an application loader either using the play.application.loader configuration property, or by depending on a module that configures one. You can add the Guice support module by adding "libraryDependencies += guice" to your build.sbt.`
	`at scala.sys.package$.error(package.scala:30)
	at play.api.ApplicationLoader$.play$api$ApplicationLoader$$loaderNotFound(ApplicationLoader.scala:44)
	at play.api.ApplicationLoader$.apply(ApplicationLoader.scala:70)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:50)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)`

Can you please help ?

**Comment by thierri** [comment]
I think you are not referencing the config file correctly. Go to the parent folder and run:
**bin**/kafka-manager -Dconfig.file=**conf**/application.conf -Dhttp.port=8080
