### ISSUE TITLE
Failed to add cluster on 3.0.0.1

### ISSUE THREAD

**Issue by rsaggino** [yahoo/CMAK#731]
Using the latest release (3.0.0.1) this happens while trying to add a cluster: 
```
2020-02-21 12:42:37,602 - [ERROR] k.m.KafkaManager - Failed on input : KMAddCluster(ClusterConfig(TEST,CuratorConfig(server:2181/cmak,100,100,1000),true,2.1.1,false,None,None,false,false,false,false,false,false,Some(ClusterTuning(Some(30),Some(2),Some(100),Some(2),Some(100),Some(2),Some(100),Some(30),Some(5),Some(4),Some(1000),Some(4),Some(1000),Some(4),Some(1000),Some(30000),Some(1000000),Some(7))),PLAINTEXT,None,None))
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /kafka-manager/mutex
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
2020-02-21 12:42:37,602 - [ERROR] k.m.ApiError$ - error : KeeperErrorCode = Unimplemented for /kafka-manager/mutex
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /kafka-manager/mutex
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)

```

Is this a configuration issue?

**Comment by akashdgoel** [comment]
I am also facing same issue and was about to open an issue for same

**Comment by patelh** [comment]
I am unable to reproduce this.  Try using the compiled binary attached to 3.0.0.2 release as asset.

**Comment by Kutim** [comment]
I am also facing same issue.
Using the latest CMAK release (3.0.0.2)

you can reproduce it with the following code:
```
$ cat docker-compose.yml 
version: '2'
services:
  zookeeper:
    image: kutim/zookeeper:3.4.14
    ports:
      - "2181:2181"
  kafka:
    image: kutim/kafka:8-stretch
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.1.78
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cmak:
    image: kutim/cmak:3.0.0.2
    ports:
      - "18007:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: password
```

kafka version :2.4.0
 @patelh

**Comment by rsaggino** [comment]
> I am unable to reproduce this. Try using the compiled binary attached to 3.0.0.2 release as asset.
The binary release works.

**Comment by 6westboy9** [comment]
I am also facing same issue

**Comment by coding-chenkaikai** [comment]
I am also facing same issue

**Comment by coding-chenkaikai** [comment]
I encountered the same problem

**Comment by pj9039** [comment]
I am using Zookeeper 3.4.10
same issue

**Comment by patelh** [comment]
@6westboy9 @coding-chenkaikai @pj9039 use the binary release...

**Comment by rsaggino** [comment]
> @6westboy9 @coding-chenkaikai @pj9039 use the binary release...
It would be great to understand what is going wrong, could you please specify how you are building it?
(Java version, os release etc.)

Thanks

**Comment by agunturu** [comment]
I ran into the same issue. As a workaround, I had to create /kafka-manager/mutex/locks and /kafka-manager/mutex/leases nodes manually. After that, I am able to add clusters.

**Comment by zheng-zy** [comment]
我用的版本是cmak-3.0.0.4，启动的时候发现同样的问题，需要在zk上手动创建/kafka-manager/mutex/locks、/kafka-manager/mutex/leases这两个节点

**Comment by 1411643015** [comment]
> 我用的版本是cmak-3.0.0.4，启动的时候发现同样的问题，需要在zk上手动创建/kafka-manager/mutex/locks、/kafka-manager/mutex/leases这两个节点

Kafka萌新请问创建的ZK节点类型是什么类型呢？

**Comment by quanghn96** [comment]
> I ran into the same issue. As a workaround, I had to create /kafka-manager/mutex/locks and /kafka-manager/mutex/leases nodes manually. After that, I am able to add clusters.

Can you explain me where did you create?

**Comment by zhigang** [comment]
- my docker image version
  - zookeeper:3.4.14
  - wurstmeister/kafka:2.12-2.4.1
  - kafkamanager/kafka-manager:3.0.0.4
- this worked for me
```
➜ docker exec -it zookeeper bash
root@98747a9eac65:/zookeeper-3.4.14# ./bin/zkCli.sh
[zk: localhost:2181(CONNECTED) 2] ls /kafka-manager
[configs, deleteClusters, clusters]
[zk: localhost:2181(CONNECTED) 3] create /kafka-manager/mutex ""
Created /kafka-manager/mutex
[zk: localhost:2181(CONNECTED) 5] create /kafka-manager/mutex/locks ""
Created /kafka-manager/mutex/locks
[zk: localhost:2181(CONNECTED) 6] create /kafka-manager/mutex/leases ""
Created /kafka-manager/mutex/leases
```

**Comment by jmilagroso** [comment]
Thanks @zhigang, was able to get it running on local with 1 zk and 2 kafka brokers.

Zookeeper 3.4.13
Kafka 2.2.1
CMAK 3.0.0.5

**Comment by jmilagroso** [comment]
> > I ran into the same issue. As a workaround, I had to create /kafka-manager/mutex/locks and /kafka-manager/mutex/leases nodes manually. After that, I am able to add clusters.
> 
> Can you explain me where did you create?

In zk cli

**Comment by mahkorayem** [comment]
> * my docker image version
>   
>   * zookeeper:3.4.14
>   * wurstmeister/kafka:2.12-2.4.1
>   * kafkamanager/kafka-manager:3.0.0.4
> * this worked for me
> 
> ```
> ➜ docker exec -it zookeeper bash
> root@98747a9eac65:/zookeeper-3.4.14# ./bin/zkCli.sh
> [zk: localhost:2181(CONNECTED) 2] ls /kafka-manager
> [configs, deleteClusters, clusters]
> [zk: localhost:2181(CONNECTED) 3] create /kafka-manager/mutex ""
> Created /kafka-manager/mutex
> [zk: localhost:2181(CONNECTED) 5] create /kafka-manager/mutex/locks ""
> Created /kafka-manager/mutex/locks
> [zk: localhost:2181(CONNECTED) 6] create /kafka-manager/mutex/leases ""
> Created /kafka-manager/mutex/leases
> ```

Worked like a charm

**Comment by lirazsh** [comment]
Still happens in 3.0.0.5. 
Fixed manually as per above solutions...

**Comment by sko00o** [comment]
Update zookeeper to 3.5+ fix this for me.

My docker image version:
* zookeeper:3.5
* wurstmeister/kafka:2.12-2.4.0
* kafkamanager/kafka-manager:3.0.0.4

**Comment by man-jiteshm-sportsbet** [comment]
> * my docker image version
>       
>       * zookeeper:3.4.14
>       * wurstmeister/kafka:2.12-2.4.1
>       * kafkamanager/kafka-manager:3.0.0.4
> 
>     * this worked for me
> 
> 
> ```
> ➜ docker exec -it zookeeper bash
> root@98747a9eac65:/zookeeper-3.4.14# ./bin/zkCli.sh
> [zk: localhost:2181(CONNECTED) 2] ls /kafka-manager
> [configs, deleteClusters, clusters]
> [zk: localhost:2181(CONNECTED) 3] create /kafka-manager/mutex ""
> Created /kafka-manager/mutex
> [zk: localhost:2181(CONNECTED) 5] create /kafka-manager/mutex/locks ""
> Created /kafka-manager/mutex/locks
> [zk: localhost:2181(CONNECTED) 6] create /kafka-manager/mutex/leases ""
> Created /kafka-manager/mutex/leases
> ```

worked for me too

**Comment by yasuolumia** [comment]
> The problem still occurs. I understand that creating mutex folder is some kind of solutions, but this should work without creating it manually. Maybe this should be created automatically, but with the option to disable as a variable.......

我也觉得不应该自己去手动创建文件夹来解决问题，按道理来说应该是自动生成的，还有，那些说升级zk版本的，生产环境的组件版本最好不要乱动。

**Comment by MananChopra3000** [comment]
Trying to upgrade the Zookeeper version to 3.9.1 and getting the same error. Gone through the above solution involves a few commands to run within the container. But when we go to prod before can we run these commands it could break prod as soon as we deploy the change.

**Comment by mananchopra** [comment]
Trying to upgrade the Zookeeper version to 3.9.1 and getting the same error. Gone through the above solution involves a few commands to run within the container. But when we go to prod before can we run these commands it could break prod as soon as we deploy the change.
