### ISSUE TITLE
Cannot create ea new cluster (KeeperErrorCode = Unimplemented for /kafka-manager)

### ISSUE THREAD

**Issue by hedgss** [yahoo/CMAK#752]
Hi

I am using the last docker image `hlebalbau/kafka-manager:latest`
I get the following error when I am trying to add a kafka cluster to kafka-manager.
```
KeeperErrorCode = Unimplemented for /kafka-manager
2020-03-16 09:10:15,813 - [INFO] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x2008308add800d8, likely server has closed socket, closing socket connection and attempting reconnect
2020-03-16 09:10:15,814 - [ERROR] k.m.KafkaManager - Failed on input : KMAddCluster(ClusterConfig(kafka-dev,CuratorConfig(zookeeper,10,100,1000),true,2.0.0,false,None,None,false,false,false,false,false,false,Some(ClusterTuning(Some(30),Some(2),Some(100),Some(2),Some(100),Some(2),Some(100),Some(30),Some(5),Some(4),Some(1000),Some(4),Some(1000),Some(4),Some(1000),Some(30000),Some(1000000),Some(7))),PLAINTEXT,None,None))
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /kafka-manager
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
2020-03-16 09:10:15,815 - [ERROR] k.m.ApiError$ - error : KeeperErrorCode = Unimplemented for /kafka-manager
org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /kafka-manager
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
        at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
        at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
        at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
        at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
        at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
2020-03-16 09:10:17,434 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...
2020-03-16 09:10:17,465 - [INFO] o.a.z.ClientCnxn - Opening socket connection to server zookeeper-lb/10.43.236.200:2181. Will not attempt to authenticate using SASL (unknown error)
2020-03-16 09:10:17,466 - [INFO] o.a.z.ClientCnxn - Socket connection established, initiating session, client: /10.42.3.67:51408, server: zookeeper-lb/10.43.236.200:2181
2020-03-16 09:10:17,469 - [INFO] o.a.z.ClientCnxn - Session establishment complete on server zookeeper-lb/10.43.236.200:2181, sessionid = 0x2008308add800d8, negotiated timeout = 40000
2020-03-16 09:10:17,470 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...
2020-03-16 09:10:17,470 - [INFO] k.m.a.KafkaManagerActor - Pruning clusters...
2020-03-16 09:10:27,415 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...
2020-03-16 09:10:37,426 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...
```
Zookeeper is available and works properly

**Comment by GuoGuang** [comment]
I encountered the same problem. Reference https://github.com/yahoo/CMAK/issues/748#issuecomment-598734547
