### ISSUE TITLE
it can not work with java 1.8.0_65

### ISSUE THREAD

**Issue by huangkaiyan10** [yahoo/CMAK#754]
it use 3.0.0.4 version CMAK with  java 1.8.0_65,but error.

2020-03-19 14:05:14,235 - [INFO] o.a.z.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
2020-03-19 14:05:14,235 - [INFO] o.a.z.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
2020-03-19 14:05:23,591 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...
2020-03-19 14:05:29,239 - [ERROR] o.a.c.ConnectionState - Connection timed out for connection string (192.168.1.231:2181,192.168.1.232:2181,192.168.1.234:2181) and timeout (15000) / elapsed (15010)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:740)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
2020-03-19 14:05:29,240 - [INFO] k.m.a.c.ClusterManagerActor - retryCount=0 maxRetries=10 zkConnect=192.168.1.231:2181,192.168.1.232:2181,192.168.1.234:2181
Uncaught error from thread [application-akka.actor.default-dispatcher-7]: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at models.navigation.QuickRoutes$.$anonfun$baseRoutes$2(QuickRoutes.scala:18)
	at models.navigation.QuickRoutes$BaseRoute.baseRouteMenuItem(QuickRoutes.scala:51)
****

**Comment by rsaggino** [comment]
Java 11 is now a requirement.
