### ISSUE TITLE
 zookeeper.request.timeout value is 0. feature enabled=

### ISSUE THREAD

**Issue by huangkaiyan10** [yahoo/CMAK#755]
i use default config,but encouter a error.

2020-03-19 14:26:38,097 - [INFO] o.a.z.ZooKeeper - Initiating client connection, connectString=192.168.1.231:2181,192.168.1.232:2181,192.168.1.234:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@3c4e79d2
2020-03-19 14:26:38,103 - [INFO] o.a.z.c.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2020-03-19 14:26:38,110 - [INFO] o.a.z.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
2020-03-19 14:26:38,120 - [INFO] o.a.z.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
2020-03-19 14:26:38,129 - [INFO] k.m.a.KafkaManagerActor - zk=192.168.1.231:2181,192.168.1.232:2181,192.168.1.234:2181
2020-03-19 14:26:38,129 - [INFO] k.m.a.KafkaManagerActor - baseZkPath=/kafka-manager
2020-03-19 14:26:38,481 - [INFO] play.api.Play - Application started (Prod)
2020-03-19 14:26:39,362 - [INFO] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:19000
2020-03-19 14:26:53,169 - [ERROR] o.a.c.ConnectionState - Connection timed out for connection string (192.168.1.231:2181,192.168.1.232:2181,192.168.1.234:2181) and timeout (15000) / elapsed (15077)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:740)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)

**Comment by bobnautic** [comment]
Any Updates to this ?
