### ISSUE TITLE
TCP port used by JMX

### ISSUE THREAD

**Issue by ppihus** [yahoo/CMAK#762]
Is there any way I could set the JMX port where CMAK tries to connect? By default it is 9099 and I have not found a way to change this.

**Comment by JimLeeee** [comment]
I got below error when trying to connecto AWS MSK. 
The port of MSK is 11001. How to modify this port in kafka-manager?  

k.m.j.KafkaJMX$ - Failed to connect to service:jmx:rmi:///jndi/rmi://b-2.vidda-kafka.f50udn.c3.kafka.us-west-2.amazonaws.com:9099/jmxrmi
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: b-2.vidda-kafka.f50udn.c3.kafka.us-west-2.amazonaws.com; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369) ~[na:1.8.0_171]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_171]
        at kafka.manager.jmx.KafkaJMX$.doWithConnection(KafkaJMX.scala:57) ~[kafka-manager.kafka-manager-1.3.3.23-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.BrokerViewCacheActor$$anonfun$kafka$manager$actor$cluster$BrokerViewCacheActor$$updateBrokerTopicPartitionsSize$1$$anonfun$apply$29$$anonfun$apply$4.apply$mcV$sp(BrokerViewCacheActor.scala:382) [kafka-manager.kafka-manager-1.3.3.23-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.BrokerViewCacheActor$$anonfun$kafka$manager$actor$cluster$BrokerViewCacheActor$$updateBrokerTopicPartitionsSize$1$$anonfun$apply$29$$anonfun$apply$4.apply(BrokerViewCacheActor.scala:379) [kafka-manager.kafka-manager-1.3.3.23-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.BrokerViewCacheActor$$anonfun$kafka$manager$actor$cluster$BrokerViewCacheActor$$updateBrokerTopicPartitionsSize$1$$anonfun$apply$29$$anonfun$apply$4.apply(BrokerViewCacheActor.scala:379) [kafka-manager.kafka-manager-1.3.3.23-sans-externalized.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.12.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.12.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
Caused by: javax.naming.ServiceUnavailableException: null
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136) ~[na:1.8.0_171]
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205) ~[na:1.8.0_171]

**Comment by sfdc-slumos** [comment]
The "Open Monitoring" JMX port provides metrics from JMX, but it is Prometheus protocol. (Came here searching for whether Prometheus fetching had been added yet.)

**Comment by hidekuma** [comment]
same problem.. AWS MSK(kafka broker) is support only 11001 port for JMX.
