### ISSUE TITLE
What Java Version can be running CMAK3.0.0.4?

### ISSUE THREAD

**Issue by AlexHU421** [yahoo/CMAK#777]
First I running in JDK8 but if I Visit the web page. The program reports an error and exits

The Error say：
`controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.UnsupportedClassVersionError: controllers/routes has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

Then I in JDK8 Error report and exit again after running the program
The Error say：
`Exception in thread "main" java.lang.UnsupportedClassVersionError: play/core/server/ProdServerStart : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
`

**Comment by patelh** [comment]
Java 11
