### ISSUE TITLE
problem while running ./sbt clean dist

### ISSUE THREAD

**Issue by suryab84** [yahoo/CMAK#839]
java version "11.0.10" 2021-01-19 LTS
Trying to install kafka manager and getting the following issue. It doesn't create the "universal" folder under the target folder.

[ERROR] [05/04/2021 12:37:38.717] [sbt-web-akka.actor.default-dispatcher-3] [akka://sbt-web/user/$a/process] Cannot run program "node": Malformed argument has embedded quote: [[\"C:\\Users\\Surya\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
akka.actor.ActorInitializationException: akka://sbt-web/user/$a/process: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:669)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:624)
        at akka.actor.ActorCell.create(ActorCell.scala:650)
        ... 7 more
Caused by: java.io.IOException: Cannot run program "node": Malformed argument has embedded quote: [[\"C:\\Users\\Surya\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at akka.contrib.process.BlockingProcess.<init>(BlockingProcess.scala:55)
        ... 16 more
Caused by: java.lang.IllegalArgumentException: Malformed argument has embedded quote: [[\"C:\\Users\\Surya\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
        at java.base/java.lang.ProcessImpl.needsEscaping(ProcessImpl.java:312)
        at java.base/java.lang.ProcessImpl.createCommandLine(ProcessImpl.java:235)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:470)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 18 more

model contains 640 documentable templates
[info] Main Scala API documentation successful.
[info] Done compiling.

**Comment by naveeen684** [comment]
Did you solved that?

**Comment by Tiakon** [comment]
I added -Djdk.lang.Process.allowAmbiguousCommands=true inside SBT_HOME\conf\sbtconfig.txt. And it worked.
[[Windows] Cannot run program "node"...](https://github.com/platypii/sbt-typescript/issues/1)
[Error when using latest JDK...](https://github.com/sbt/sbt-js-engine/issues/68)
