### ISSUE TITLE
sbt clean dist error

### ISSUE THREAD

**Issue by sanabargaoui** [yahoo/CMAK#868]
I have OpenJDK version "11.0.13" 
and I get this error

`copying runtime jar...
[info] Loading settings for project cmak-build from plugins.sbt ...
[info] Loading project definition from C:\CMAK\project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to cmak (in build file:/C:/CMAK/)
[success] Total time: 3 s, completed Dec 28, 2021, 11:36:29 PM
[info] Wrote C:\CMAK\target\scala-2.12\cmak_2.12-3.0.0.5.pom
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Main Scala API documentation to C:\CMAK\target\scala-2.12\api...
[info] Compiling 136 Scala sources and 2 Java sources to C:\CMAK\target\scala-2.12\classes ...
model contains 640 documentable templates
[info] LESS compiling on 1 source(s)
[ERROR] [12/28/2021 23:37:30.352] [sbt-web-akka.actor.default-dispatcher-5] [akka://sbt-web/user/$a/process] Cannot run program "node": Malformed argument has embedded quote: [[\"C:\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
akka.actor.ActorInitializationException: akka://sbt-web/user/$a/process: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
        at akka.actor.ActorCell.create(ActorCell.scala:669)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:624)
        at akka.actor.ActorCell.create(ActorCell.scala:650)
        ... 7 more
Caused by: java.io.IOException: Cannot run program "node": Malformed argument has embedded quote: [[\"C:\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at akka.contrib.process.BlockingProcess.<init>(BlockingProcess.scala:55)
        ... 16 more
Caused by: java.lang.IllegalArgumentException: Malformed argument has embedded quote: [[\"C:\\CMAK\\app\\assets\\stylesheets\\index.less\",\"stylesheets\\index.less\"]]
        at java.base/java.lang.ProcessImpl.needsEscaping(ProcessImpl.java:321)
        at java.base/java.lang.ProcessImpl.createCommandLine(ProcessImpl.java:235)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:479)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 18 more

[info] Done compiling.
[info] Main Scala API documentation successful.
[error] java.util.concurrent.TimeoutException: Futures timed out after [2 hours]
[error]         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[error]         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[error]         at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
[error]         at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[error]         at scala.concurrent.Await$.result(package.scala:146)
[error]         at com.typesafe.sbt.jse.SbtJsTask$.$anonfun$jsSourceFileTask$4(SbtJsTask.scala:330)
[error]         at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
[error]         at com.typesafe.sbt.jse.SbtJsTask$.$anonfun$jsSourceFileTask$1(SbtJsTask.scala:302)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (Web-assets / less) java.util.concurrent.TimeoutException: Futures timed out after [2 hours]
[error] Total time: 7261 s (02:01:01), completed Dec 29, 2021, 1:37:31 AM`

target directory is created but there's no universal directory.

**Comment by thakurudit** [comment]
Try running with admin rights

**Comment by duna05** [comment]
I have the same problem and I ran with admin rights, It doesn't work

**Comment by houyuanjie** [comment]
Try `sbt -Djdk.lang.Process.allowAmbiguousCommands=true clean dist`
